item {
    id: 1
    name: 'AlCan'
}

item {
    id: 2
    name: 'Others'
}

item {
    id: 3
    name: 'PaperCup'
}

item {
    id: 4
    name: 'PlasticBottle'
}

item {
    id: 5
    name: 'PlasticCup'
}